#!/usr/bin/env python
# coding: utf-8

# In[9]:


get_ipython().system('pip install yfinance==0.1.67')
#!pip install pandas==1.3.3
#!pip install requests==2.26.0
get_ipython().system('mamba install bs4==4.10.0 -y')
#!pip install plotly==5.3.1


# In[10]:


import yfinance as yf
import pandas as pd
import requests
from bs4 import BeautifulSoup
import plotly.graph_objects as go
from plotly.subplots import make_subplots


# In[11]:


def make_graph(stock_data, revenue_data, stock):
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, subplot_titles=("Historical Share Price", "Historical Revenue"), vertical_spacing = .3)
    stock_data_specific = stock_data[stock_data.Date <= '2021--06-14']
    revenue_data_specific = revenue_data[revenue_data.Date <= '2021-04-30']
    fig.add_trace(go.Scatter(x=pd.to_datetime(stock_data_specific.Date, infer_datetime_format=True), y=stock_data_specific.Close.astype("float"), name="Share Price"), row=1, col=1)
    fig.add_trace(go.Scatter(x=pd.to_datetime(revenue_data_specific.Date, infer_datetime_format=True), y=revenue_data_specific.Revenue.astype("float"), name="Revenue"), row=2, col=1)
    fig.update_xaxes(title_text="Date", row=1, col=1)
    fig.update_xaxes(title_text="Date", row=2, col=1)
    fig.update_yaxes(title_text="Price ($US)", row=1, col=1)
    fig.update_yaxes(title_text="Revenue ($US Millions)", row=2, col=1)
    fig.update_layout(showlegend=False,
    height=900,
    title=stock,
    xaxis_rangeslider_visible=True)
    fig.show()


# In[12]:


tesla = yf.Ticker("TSLA")


# In[13]:


tesla_data = tesla.history(period="max")


# In[14]:


tesla_data.reset_index(inplace=True)
tesla_data.head()


# #### QUESTION 2

# In[16]:


url= "https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue"
html_data=requests.get(url).text


# In[17]:


soup = BeautifulSoup(html_data,"html5lib")


# In[18]:


tesla_revenue= pd.read_html(url, match="Tesla Quarterly Revenue", flavor='bs4')[0]
tesla_revenue=tesla_revenue.rename(columns = {'Tesla Quarterly Revenue(Millions of US $)': 'Date', 'Tesla Quarterly Revenue(Millions of US $).1': 'Revenue'}, inplace = False)
tesla_revenue["Revenue"] = tesla_revenue["Revenue"].str.replace(",","").str.replace("$","")
tesla_revenue.head()


# In[19]:


tesla_revenue


# In[20]:


tesla_revenue.dropna(inplace=True)
tesla_revenue.tail()


# #### QUESTION 3

# In[21]:


gamestop = yf.Ticker("GME")


# In[22]:


gme_data=gamestop.history(period="max")


# In[23]:


gme_data.reset_index(inplace=True)
gme_data.head()


# #### QUESTION 4

# In[24]:


url="https://www.macrotrends.net/stocks/charts/GME/gamestop/revenue"
html_data=requests.get(url).text


# In[25]:


soup = BeautifulSoup(html_data,"html5lib")


# In[26]:


gme_revenue= pd.read_html(url, match="GameStop Quarterly Revenue", flavor='bs4')[0]
gme_revenue=gme_revenue.rename(columns = {'GameStop Quarterly Revenue(Millions of US $)': 'Date', 'GameStop Quarterly Revenue(Millions of US $).1': 'Revenue'}, inplace = False)
gme_revenue["Revenue"] = gme_revenue["Revenue"].str.replace(",","").str.replace("$","")


# In[27]:


gme_revenue.dropna(inplace=True)
gme_revenue.tail()


# #### QUESTION 5

# In[29]:


make_graph(tesla_data, tesla_revenue, 'Tesla Stock Data Graph')


# In[30]:


make_graph(gme_data, gme_revenue, 'GameStop Stock Data Graph')


# In[ ]:




